name: Release Swift Package

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release Swift
    runs-on: ubuntu-latest
    outputs:
      tokensversion: ${{ steps.output-tokens-version.outputs.tokensversion }}
      tokensshoulddeploy: ${{ contains(fromJson(steps.changesets.outputs.publishedPackages).*.name, '@sebgroup/green-tokens') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Mock Changeset
        id: changesets
        run: |
          echo "publishedPackages=[{\"name\": \"@sebgroup/green-angular\", \"version\": \"0.6.0\"}]" >> "$GITHUB_OUTPUT"

      - name: Output green-tokens versions
        if: ${{ contains(fromJson(steps.changesets.outputs.publishedPackages).*.name, '@sebgroup/green-tokens') }}
        id: output-tokens-version
        run: echo "tokensversion=$(jq -r '.[] | select(.name=="@sebgroup/green-tokens").version' <<< '${{ steps.changesets.outputs.publishedPackages }}')" >> "$GITHUB_OUTPUT"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.tokensshoulddeploy == true }}
    steps:
      - name: Test
        run: echo '${{ needs.release.outputs.tokensshoulddeploy }} ${{ needs.release.outputs.tokensversion }}'
